// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pandos.proto

package pandos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import raftpb "github.com/coreos/etcd/raft/raftpb"
import empty "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SnapshotData struct {
	Entries              []*raftpb.Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SnapshotData) Reset()         { *m = SnapshotData{} }
func (m *SnapshotData) String() string { return proto.CompactTextString(m) }
func (*SnapshotData) ProtoMessage()    {}
func (*SnapshotData) Descriptor() ([]byte, []int) {
	return fileDescriptor_pandos_0217c22a72582719, []int{0}
}
func (m *SnapshotData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SnapshotData.Unmarshal(m, b)
}
func (m *SnapshotData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SnapshotData.Marshal(b, m, deterministic)
}
func (dst *SnapshotData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SnapshotData.Merge(dst, src)
}
func (m *SnapshotData) XXX_Size() int {
	return xxx_messageInfo_SnapshotData.Size(m)
}
func (m *SnapshotData) XXX_DiscardUnknown() {
	xxx_messageInfo_SnapshotData.DiscardUnknown(m)
}

var xxx_messageInfo_SnapshotData proto.InternalMessageInfo

func (m *SnapshotData) GetEntries() []*raftpb.Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func init() {
	proto.RegisterType((*SnapshotData)(nil), "pandos.SnapshotData")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PandosGossipClient is the client API for PandosGossip service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PandosGossipClient interface {
	Receive(ctx context.Context, in *raftpb.Message, opts ...grpc.CallOption) (*empty.Empty, error)
}

type pandosGossipClient struct {
	cc *grpc.ClientConn
}

func NewPandosGossipClient(cc *grpc.ClientConn) PandosGossipClient {
	return &pandosGossipClient{cc}
}

func (c *pandosGossipClient) Receive(ctx context.Context, in *raftpb.Message, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pandos.PandosGossip/Receive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PandosGossipServer is the server API for PandosGossip service.
type PandosGossipServer interface {
	Receive(context.Context, *raftpb.Message) (*empty.Empty, error)
}

func RegisterPandosGossipServer(s *grpc.Server, srv PandosGossipServer) {
	s.RegisterService(&_PandosGossip_serviceDesc, srv)
}

func _PandosGossip_Receive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(raftpb.Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PandosGossipServer).Receive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pandos.PandosGossip/Receive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PandosGossipServer).Receive(ctx, req.(*raftpb.Message))
	}
	return interceptor(ctx, in, info, handler)
}

var _PandosGossip_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pandos.PandosGossip",
	HandlerType: (*PandosGossipServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Receive",
			Handler:    _PandosGossip_Receive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pandos.proto",
}

func init() { proto.RegisterFile("pandos.proto", fileDescriptor_pandos_0217c22a72582719) }

var fileDescriptor_pandos_0217c22a72582719 = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8e, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x15, 0x61, 0x17, 0x62, 0x45, 0xc8, 0x41, 0xa4, 0x5e, 0x64, 0x2f, 0x7a, 0x31, 0x81,
	0x55, 0xf0, 0x05, 0x5a, 0x3c, 0x09, 0x52, 0x9f, 0x20, 0x49, 0xa7, 0x69, 0xc0, 0x66, 0x42, 0x66,
	0x2a, 0xf4, 0xed, 0xc5, 0x84, 0x5e, 0x66, 0xf8, 0xe7, 0xe7, 0x1b, 0x3e, 0xd1, 0x24, 0x13, 0x47,
	0x24, 0x95, 0x32, 0x32, 0xca, 0x43, 0x4d, 0xed, 0x8b, 0x0f, 0x3c, 0xaf, 0x56, 0x39, 0x5c, 0xb4,
	0xc3, 0x0c, 0x48, 0x1a, 0xd8, 0x8d, 0x3a, 0x9b, 0x89, 0xcb, 0x48, 0xb6, 0xac, 0x8a, 0xb5, 0x0f,
	0x1e, 0xd1, 0xff, 0x80, 0x2e, 0xc9, 0xae, 0x93, 0x86, 0x25, 0xf1, 0x56, 0xcb, 0xd3, 0xbb, 0x68,
	0xbe, 0xa3, 0x49, 0x34, 0x23, 0x77, 0x86, 0x8d, 0x7c, 0x12, 0x47, 0x88, 0x9c, 0x03, 0xd0, 0xfd,
	0xe5, 0xe3, 0xd5, 0xf3, 0xf5, 0xf9, 0x46, 0xd5, 0x8f, 0xaa, 0x8f, 0x9c, 0xb7, 0x61, 0x6f, 0xcf,
	0x9d, 0x68, 0xbe, 0x8a, 0xce, 0x07, 0x12, 0x85, 0x24, 0xdf, 0xc4, 0x71, 0x00, 0x07, 0xe1, 0x17,
	0xe4, 0xed, 0x8e, 0x7c, 0x02, 0x91, 0xf1, 0xd0, 0xde, 0xa9, 0xaa, 0xa0, 0x76, 0x05, 0xd5, 0xff,
	0x2b, 0x9c, 0x2e, 0xec, 0xa1, 0x5c, 0x5e, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x22, 0x9e, 0x59,
	0xd2, 0xe9, 0x00, 0x00, 0x00,
}
